# Generated by Django 4.2.11 on 2025-05-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='discription',
            new_name='description',
        ),
    ]
