# Generated by Django 5.2.1 on 2025-05-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0003_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
