# Generated by Django 5.2.1 on 2025-05-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0004_comment_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="resource",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
