# Generated by Django 5.2.1 on 2025-05-31 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0005_remove_comment_is_approved_resource_is_approved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_resources", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together={("user", "resource")},
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
