# Generated by Django 5.2.1 on 2025-05-31 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0006_resource_likes_alter_comment_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together=set(),
        ),
    ]
