# Generated by Django 5.2.3 on 2025-07-09 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_comment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='external_url',
            field=models.URLField(blank=True, help_text='اگر فایل آپلود نمی\u200cکنید، آدرس URL وارد کنید.', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word Document'), ('ppt', 'PowerPoint'), ('video', 'Video'), ('image', 'Image'), ('audio', 'Audio'), ('link', 'External Link'), ('other', 'Other')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='instructor_name',
            field=models.CharField(blank=True, help_text='نام مدرس یا ارائه\u200cدهنده منبع (اختیاری)', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.category'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/files/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, to='resources.tag'),
        ),
    ]
