# Generated by Django 5.2.4 on 2025-07-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_resource_privacy_userprofile_skill_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='teachable',
            field=models.BooleanField(default=False, help_text='آیا این مهارت را میتوانید تدریس کنید؟'),
        ),
    ]
