# Generated by Django 5.2.4 on 2025-07-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_skill_teachable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='year',
        ),
        migrations.AddField(
            model_name='achievement',
            name='end_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='start_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='teachable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'ترجیح می\u200cدهم نگویم')], max_length=6),
        ),
    ]
