# Generated by Django 5.2.4 on 2025-07-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_resourcefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
    ]
