# Generated by Django 5.2.4 on 2025-08-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_remove_resource_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255, verbose_name='مدرک تحصیلی')),
                ('institution', models.CharField(max_length=255, verbose_name='دانشگاه یا موسسه')),
                ('start_year', models.PositiveIntegerField(verbose_name='سال شروع')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال پایان')),
                ('description', models.TextField(blank=True, help_text='اختیاری. مثلا عنوان پایان\u200cنامه یا افتخارات.', verbose_name='توضیحات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='resources.userprofile')),
            ],
            options={
                'verbose_name': 'مدرک تحصیلی',
                'verbose_name_plural': 'سوابق تحصیلی',
                'ordering': ['-start_year'],
            },
        ),
    ]
